n=input("Enter the String having (.) and (,) :")
m=n.split(",")
#print(m)
n='#'.join(m)
#print(n)
o=n.split(".")
#print(o)
n=','.join(o)
#print(n)
p=n.split("#")
#print(p)
n='.'.join(p)
#print(n)
print("After the Swapping (.) and (,) New String is :",n)
